spring: 
  profiles:
    active:
      - dev
---
server:
  port: 7001

spring:
  profiles: dev
  application: 
    name: demo-config-eureka
eureka:
  instance:
    hostname: eureka7001.com
  client:
    # 自己不注册进服务列表
    register-with-eureka: false
    # 不通过eureka获取注册信息
    fetch-registry: false
    service-url:
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001

spring:
  profiles: test
  application:
    name: demo-config-eureka
eureka:
  instance:
    hostname: eureka7001.com
  client:
    # 自己不注册进服务列表
    register-with-eureka: false
    # 不通过eureka获取注册信息
    fetch-registry: false
    service-url:
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/